trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet restore ./FarmaciaDevOps/FarmaciaDevOps.csproj
  displayName: 'Restore dependencies'

- script: dotnet build ./FarmaciaDevOps/FarmaciaDevOps.csproj
  displayName: 'Build project'

- script: docker build -t farmacia-api .
  displayName: 'Construir imagen Docker'
