trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build
  displayName: 'Build project'